### ISSUE TITLE
Multiple languages would be super

### ISSUE THREAD

**Issue by IamTheRichie** [builtbybel/ThisIsWin11#1]
Multiple languages would be super

How do the texts come about?
Where do I find them? 

Then I could simply translate the texts and words into German.

**Comment by Belim** [comment]
it is too early to translate the gui, because it is still under development. there might be some changes and we would have to translate too many strings again. but it will come 😁

**Comment by Vichingo455** [comment]
> Multiple languages would be super
> 
> How do the texts come about? Where do I find them?
> 
> Then I could simply translate the texts and words into German.

You can find it in some instructions like:
element.Text("text");
