### ISSUE TITLE
TaskbarSize revert back to normal

### ISSUE THREAD

**Issue by nicedevil007** [builtbybel/ThisIsWin11#102]
hey guys, I accidentially resized the taskbar to small with this tool (didn't uncheck the option).
It looks terrible on the lower right corner now, so I want to switch back to normal size.

The recent TaskbarSi DWORD Entry in registry wont fix it, how can I just change this option with ThisIsWin11?

![image](https://user-images.githubusercontent.com/17103076/148644778-f52717ae-32a2-44d7-8d79-2cbbc5fb76f4.png)

**Comment by Belim** [comment]
Hi, 
just undo changes as described here https://github.com/builtbybel/ThisIsWin11/issues/94

**Comment by nicedevil007** [comment]
Ty, worked!
