### ISSUE TITLE
Windows 11 File Explorer

### ISSUE THREAD

**Issue by SemihhCall1903** [builtbybel/ThisIsWin11#107]
How to return Windows 11 File Explorer. Please say to me
![resim_2022-01-12_012132](https://user-images.githubusercontent.com/77378627/149030662-c765f5cf-7740-41ef-b663-04e27e997cc0.png)

**Comment by Belim** [comment]
Goto **Extensions** and uncheck Plugin **Enable Classic Context menus** ...

**Comment by SemihhCall1903** [comment]
That's not exactly what i meant .I doing changed taskbar.If you known about that please to say me 
![Ekran Görüntüsü (47)](https://user-images.githubusercontent.com/77378627/149378379-4fea52d9-ff67-4818-9a91-10cc2c1f2cd4.png)

**Comment by Belim** [comment]
I don't understand where the problem is, except that the icons are aligned left and not middle. You can turn back all the settings in the Customization > Personalization module of TIW11
