### ISSUE TITLE
Not able to reinstall windows store(?)

### ISSUE THREAD

**Issue by lenti21** [builtbybel/ThisIsWin11#108]
Hi! I deleted some systemapps and now i dont have store. Tried some commands in powershell but it says that it cannot find "appx manifest". Do i need to restore my pc? Thanks

**Comment by Belim** [comment]
Goto **Automation** module and run script **Reinstall all built-in apps** or just put this in a powershell instance
`Get-AppxPackage -allusers Microsoft.WindowsStore | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}`
