### ISSUE TITLE
Running Fix Issues cleared all my selections 

### ISSUE THREAD

**Issue by AplhaSlayer1964** [builtbybel/ThisIsWin11#118]
Had all the selections I wanted then clicked fix issues and everything was unselected and applied. Now my task bar is stuck small and I have the windows 10 file explorer. Clicking restore defaults does nothing. RIP

**Comment by Belim** [comment]
https://github.com/builtbybel/ThisIsWin11/issues/102

**Comment by AplhaSlayer1964** [comment]
> #102

The solution shown didn't work and that wasn't the main problem that occurred. I selected what I wanted and it unchecked everything and applied that instead.

**Comment by AplhaSlayer1964** [comment]
I had to manually go into the registry to fix the small taskbar but it also changed everything else witch is very annoying. I now have to go look up all the registry files it changed. It also didn't create a restore point like the check box I had selected said it would do.
