### ISSUE TITLE
TF happend to my taskbar

### ISSUE THREAD

**Issue by Advik-B** [builtbybel/ThisIsWin11#119]
![image](https://user-images.githubusercontent.com/86160411/151368187-43bf9cff-f9db-4ed6-8b93-346ae4c0f653.png)
WHY IS IT SOOO SMALL

**Comment by Advik-B** [comment]
![image](https://user-images.githubusercontent.com/86160411/151369586-cfedbf84-b067-482c-b7d5-b66da03fd927.png)
Dude it just broke my entire PC

**Comment by Belim** [comment]
https://github.com/builtbybel/ThisIsWin11/issues/102
