### ISSUE TITLE
Clean up 11 empty pinned items

### ISSUE THREAD

**Issue by icecoffeeabell1835** [builtbybel/ThisIsWin11#13]
When I first installed Windows 11 locally on my machine, I saw this Start menu. In total there are 11 pinned items that have no icon by default. 

It is annoying to always manually delete the empty pinned items, can you add a function that automatically deletes these 11 empty pinned items automatically? Does anyone know in general what these 11 empty pinned items are, what are the apps that the user can't see without an internet connection?

![11](https://user-images.githubusercontent.com/91980861/136227088-d05e9004-d95b-44d0-8909-ae92517e29ee.PNG)

![112](https://user-images.githubusercontent.com/91980861/136227828-a1f583c2-338e-4102-8093-a08e94a3d6f4.PNG)

**Comment by Belim** [comment]
all pre-installed apps on win11 cant be used with no internet connection because they aren't real apps, just stubs.

https://www.ghacks.net/2021/09/20/some-native-windows-11-apps-require-an-internet-connection-on-first-launch/

**Comment by icecoffeeabell1835** [comment]
> 
> 
> all pre-installed apps on win11 cant be used with no internet connection because they aren't real apps, just stubs.
> 
> https://www.ghacks.net/2021/09/20/some-native-windows-11-apps-require-an-internet-connection-on-first-launch/

Understand and why did Microsoft add this nonsense? 

Firstly it looks ugly and secondly my machine has more than 2 TB of storage, I would have no problem with it if they are real applications and then I uninstall them later. But this behavior just looks ugly.

I have now test connected to the internet and there are these 11 apps that are then no longer empty pinned items. Is there a possibility to completely remove this nonsense automatically?
![111](https://user-images.githubusercontent.com/91980861/136235537-d5086392-f43b-4a39-80f1-de09e882763a.PNG)
