### ISSUE TITLE
how do I fix taskbar being small 

### ISSUE THREAD

**Issue by Charmander989** [builtbybel/ThisIsWin11#133]
I was going through these tweaks and it didn't really bring up it saying it was going to remove the microsoft store itself, I'm going to do the system restore it does so it isn't a big deal but it's just annoying that it doesn't say in full detail that it deletes it, it also shrunk my taskbar so they're microscopic and I can't even see the date since it gets cut off by the bottom of my screen, It's probably because I'm on 1722x1070 but still

**Comment by acb6691** [comment]
I am facing the same problem: the taskbar and icons have shrunk and half of the date is not visible anymore.
Any remedy suggestion would be very much appreciated.

**Comment by Charmander989** [comment]
> I am facing the same problem: the taskbar and icons have shrunk and half of the date is not visible anymore. Any remedy suggestion would be very much appreciated.
I thankfully had a restore point that I setup before doing all the debloating since I didn't know if it was going to effect my pc but it seems like the "this is windows 11" didn't create that restore point, I am going to try it again, I'm guessing I didn't go through it correctly but still it said it created a restore point and it didn't or at least I couldn't find it which can cause extreme issues,

the only thing I can think about to fix this problem is to look and see if it actually gave you a restore point for you 
https://youtu.be/KsMD1VBTl_M?t=101
this shows you how to see all possible restore points windows has

**Comment by Belim** [comment]
guys, please just [browse](https://github.com/builtbybel/ThisIsWin11/issues?q=is%3Aissue+is%3Aclosed) the closed issues. or just undo the changes. its a simple click.....
