### ISSUE TITLE
taskbar being small

### ISSUE THREAD

**Issue by keanehilario** [builtbybel/ThisIsWin11#134]
.

**Comment by Charmander989** [comment]
maybe try a restart, try and go into windows boot mode and click repair, I don't really know how else to do it unless you have a restore point but that fucked up my pc when I did it ( I had the same problem as you) and  I can't get snipping tool to work and microsoft store, I'm going to try the windows repair sometime soon

**Comment by MDSilviu** [comment]
You can fix it by following this instructions https://www.lifewire.com/change-taskbar-size-in-windows-11-5190012

**Comment by ejnshtein** [comment]
Probably you checked everything and it checked the **Small Taskbar and icons** option

![image](https://user-images.githubusercontent.com/18352350/159078528-874f347b-837f-406b-8c6e-e1a3ee84f03d.png)

To fix that, use the link above, yeah.

Maybe this option should be off by default 🤔

**Comment by Kalahee** [comment]
Open RegEdit.
Go to "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced\".
Delete "TaskbarSi".
Restart.

**Comment by Belim** [comment]
just reset the applied setting
