### ISSUE TITLE
File explorer header borderline broken

### ISSUE THREAD

**Issue by TheArkhomDestroyer** [builtbybel/ThisIsWin11#143]
![The problam](https://user-images.githubusercontent.com/103296859/162553302-5fe98670-e1da-40ec-8d78-1c807cc2c013.png)

I'm not sure what happened but my file but as you can see, something went horribly wrong and nothing I do is fixing it. This is driving me up a wall.

**Comment by Belim** [comment]
i assume you've enabled the file explorer tabs with vive tool?
So i would recommend reverting the option "Enable Windows 10 File Explorer".

**Comment by samiscold** [comment]
It won't fix!
