### ISSUE TITLE
Power plan automatically reverting to high performance

### ISSUE THREAD

**Issue by spxctreofficial** [builtbybel/ThisIsWin11#151]
Before using ThisIsWin11, I already had the Ultimate Performance enabled inside of my Power plan settings. After using, however, I presume that a task has been created inside of Task Scheduler that automatically reverts the power plan to High performance, and I can't seem to find the task and disable it. Any ideas?

**Comment by lol0920620797** [comment]
Will there be a Chinese version in the future? THX
