### ISSUE TITLE
Disable automatic restart/reboot after Windows Update

### ISSUE THREAD

**Issue by ghnp5** [builtbybel/ThisIsWin11#159]
Is there a way to stop Windows 11 from automatically restarting after installing Updates, using this tool?
If not, do you know any tool that supports doing it?

I don't want disable Updates. I just want to restart Windows whenever I ready, and not while I'm away from the PC.

I used to be able to do this by replacing the `Reboot` file with a folder inside `C:\Windows\System32\Tasks\Microsoft\Windows\UpdateOrchestrator`, but they keep changing these things, so it's not possible anymore.

Thank you!

**Comment by Belim** [comment]
not with this app
