### ISSUE TITLE
Get Started [MicrosoftWindows.Client.CBS_cw5n1h2txyewy] cannot be removed/disabled

### ISSUE THREAD

**Issue by ghost** [builtbybel/ThisIsWin11#16]
![getstarted](https://user-images.githubusercontent.com/88926467/136737730-769ed26e-ba8f-46ed-9fa4-6f4c84ab2962.png)

How do you get rid of it?

**Comment by Belim** [comment]
take a look [here](https://github.com/builtbybel/ThisIsWin11/issues/13)

**Comment by lurkingaround** [comment]
No it doesn't, it's still there.

**Comment by andreimd87** [comment]
this "get started" app and client.CBS comes with windows feature experience pack which can be removed with dism or dism++ tool. after restart it will get removed. however start menu and taskbar features are a part of it. so keep in mind to install a third party start menu like startallback before removing windows feature experience pack.

**Comment by Darthpenguin** [comment]
Maybe not the best solution. But I booted a live Linux distro from USB and mounted the local drive. Then I deleted 'MicrosoftWindows.Client.CBS_cw5n1h2txyewy' from <drive>\Windows\SystemApps. May not be a permanent solution but seems to work so far.

**Comment by mrdibri** [comment]
Just end Textinputhost.exe in TaskManager, 
Than go to the File Location in C:\Windows\SystemApps ,
and Take Ownership of  "MicrosoftWindows.Client.CBS_cw5n1h2txyewy" (Textinputhost.exe)
Than you can Remove it,That Worked for me

**Comment by farag2** [comment]
This is a built-in system component. you cannot removed = you mustn't. https://borncity.com/win/2021/01/31/windows-10-windows-feature-experience-pack-insides/
Why were you trying to destroy your Windows?..

**Comment by MuhammadAbrarx** [comment]
@mrdibri thanks ,, your solution worked flawlessly, just had to use process hacker to kill, and what is found is that it an emoji picker helper or something, no threat to windows or it's stability ..  no worries my system running just fine.
