### ISSUE TITLE
Cannot use Microsoft account to play games like Minecraft - locked out of some services

### ISSUE THREAD

**Issue by squaredindex** [builtbybel/ThisIsWin11#166]
This was mentioned in https://github.com/builtbybel/ThisIsWin11/issues/84 but dismissed too quickly.
Minecraft for Windows now requires a Microsoft account and Minecraft will try to connect you so you can sign in or create an account from what I can tell and it seems that after using ThisIsWin11 that this connection is blocked perhaps.

I'm not exactly sure which setting specifically I need to undo in order to resolve this. I understand why you would generally want to block it, however, it seems like it's required for some software.

**Comment by cp6tbix0r** [comment]
Look it up here: https://github.com/builtbybel/ThisIsWin11/issues/53

**Comment by squaredindex** [comment]
Update: looking at this again, even after signing into my Microsoft account on the store, I'm unable to connect to Microsoft via Minecraft and I get the following error `error Code: 0x80070057 code: Deep Ocean`. All I can think is that there is something that's either been removed or blocked that no longer allows it to connect to Microsoft in the manner that it requires.

**Comment by lewgrant** [comment]
I too am unable to sign into minecraft after using ThisIsWin11 - in my case it's the windows app store version of minecraft. I was also signed out of the xbox companion app but was able to sign back in there with no problem.

**Comment by squaredindex** [comment]
@lewgrant I believe I may have found the "solution" to this.
It seems as though Microsoft now forces you to install both of their Xbox apps as dependencies for playing any game that requires a Microsoft login.

It may also require you to reinstall and stop blocking their "necessary background processes".

Honestly, I've concluded it's not worth installing all this spyware, I just no longer have access to a game I purchased from another company back when it was in alpha over a decade ago.

Here is the message  got back from Microsoft support regarding the issue on Windows 11:

Ensure you have the Xbox Console Companion installed: [https://aka.ms/xboxconsolecompanion](https://aka.ms/xboxconsolecompanion)
**Although this is running on your PC, the Xbox Console Companion app has dependencies required for proper authentication of your Microsoft Account.**

Once you have the application installed, make sure you are logged into the Xbox Companion App.
After logging into the Companion App, try logging into the Minecraft Launcher.
- Install the Xbox Application: [https://aka.ms/DLxboxapp](https://aka.ms/DLxboxapp)

Similar to the Xbox Console Companion, while this is running on your PC, the Xbox Console Companion app has dependencies required for proper authentication of your Microsoft Account.

Make sure to log into the Xbox Application prior to attempting to log into the Minecraft Launcher.
If you're encountering errors when attempting to download either of these applications, they are often times caused by necessary background processes that were blocked from being downloaded onto your computer:
- Xbox Identity Provider: [https://aka.ms/XboxIdentityProvider](https://aka.ms/XboxIdentityProvider)
- Xbox Live In Game Experience: [https://aka.ms/XboxLiveInGame](https://aka.ms/XboxLiveInGame)
- Gaming Services: [https://aka.ms/GetGamingServices](https://aka.ms/GetGamingServices)
- Feedback Hub: [https://aka.ms/DLFeedbackHub](https://aka.ms/DLFeedbackHub)
You will also want to look in the services running in your task manager to make sure the previously listed services are running.
