### ISSUE TITLE
[BUG] Partially hidden taskbar icons and clock

### ISSUE THREAD

**Issue by kenalb** [builtbybel/ThisIsWin11#169]
When selecting the "Small Taskbar and icons" customization option the taskbar time and settings get cropped, other taskbar icons appear unaffected.
![Taskbar](https://user-images.githubusercontent.com/109924801/180667422-b6e68d32-2108-477f-8de1-f2d1ae1eb31d.png)

**Comment by VulcanRR** [comment]
I have the same issue, any fixes?

**Comment by VulcanRR** [comment]
I found the fix , https://www.youtube.com/watch?v=RswaXcWWCo0 ,time stamp 5:50 is the solution

if renaming to TaskbarSi doesn't seem to work it's probably because there's already a value called TaskbarSi, change that value and that's it, it's fixed. 

you're welcome :)

**Comment by kenalb** [comment]
> I found the fix , https://www.youtube.com/watch?v=RswaXcWWCo0 ,time stamp 5:50 is the solution
> 
> if renaming to TaskbarSi doesn't seem to work it's probably because there's already a value called TaskbarSi, change that value and that's it, it's fixed.
> 
> you're welcome :)
I attempted those changes and found that it didn't have any effect on the appearance of the taskbar for me.

**Comment by tectiv3** [comment]
basically to revert it back to default set it to 1
```
- Resize icons on taskbar:
Location in registry: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
Small taskbar – TaskbarSi value 0
Default taskbar – TaskbarSi value 1
Large taskbar – TaskbarSi value 2
```

**Comment by zeff9801** [comment]
i have the same issue, waiting for it to get resolved

**Comment by dgpapagian** [comment]
> basically to revert it back to default set it to 1
> 
> ```
> - Resize icons on taskbar:
> Location in registry: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
> Small taskbar – TaskbarSi value 0
> Default taskbar – TaskbarSi value 1
> Large taskbar – TaskbarSi value 2
> ```

This solution works. Just make sure that you restart win explorer afterwards

**Comment by Stuart88** [comment]
> basically to revert it back to default set it to 1
> 
> ```
> - Resize icons on taskbar:
> Location in registry: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
> Small taskbar – TaskbarSi value 0
> Default taskbar – TaskbarSi value 1
> Large taskbar – TaskbarSi value 2
> ```

Helpful, thanks.

I find it amazing that this guy has released software that makes registry edits, but does not offer a way to undo it.
