### ISSUE TITLE
Uninstall/Disable Widgets

### ISSUE THREAD

**Issue by ghost** [builtbybel/ThisIsWin11#17]
Is there a way to disable them? like I did it with a Command but I don't know what it does.. besides disabling the widget..
If you hide it in the settings it still runs in the background even if you don't use it  :((

this is what I did to remove it (some indian tech youtuber did a tut with just saying it removes the useless widgets)
_`winget uninstall "windows web experience pack"`_

**Comment by Belim** [comment]
you're right. the widgets feature can be uninstalled via winget/ps.
maybe a new tweak!?
