### ISSUE TITLE
Taskbar icons became tiny

### ISSUE THREAD

**Issue by spogulis** [builtbybel/ThisIsWin11#18]
After applying all system settings as admin user and restarting, taskbar icons became tiny.

**Comment by Belim** [comment]
yes, here too. seems to be a w11bug

**Comment by spogulis** [comment]
> 
> 
> yes, here too. seems to be a w11bug

Turns out this is a setting in the app. Was having trouble restoring it because initially set all settings via an admin account while I, myself, use a limited account. This difference writes to a different HKEY_LOCAL_USER registry entry depending on the user who opens the app.
