### ISSUE TITLE
some common issues and annoyance in windows11

### ISSUE THREAD

**Issue by Triplesweet** [builtbybel/ThisIsWin11#185]
1. web search on start (and it forcefully uses edge)  [this](https://www.guidingtech.com/how-to-disable-web-search-results-from-start-menu-in-windows-11/) one works (tried after a fresh install and update)
2. the new right click menu looks bad, and so many people want the old one back. [this](https://www.thewindowsclub.com/get-old-right-click-context-menu-back-on-windows-11) gets the job done
3. there is this stupid bug on so many laptops for amd GPUs, windows for what ever reason replace the real drivers with the generic ones and break the adrenaline, so we need to reinstall it again and again, and for this, [this](https://community.amd.com/t5/drivers-software/windows-update-keeps-overwriting-my-installed-amd-driver/td-p/504648?lightbox-message-images-504681=62077iE05BF74EA5AF3539) can help

**Comment by Belim** [comment]
no relation to the app
