### ISSUE TITLE
Configuration file for admins would be great

### ISSUE THREAD

**Issue by htcfreek** [builtbybel/ThisIsWin11#2]
It would be great if administrators are allow to configure which thing should be shown/not shown.

**Example(s):**
- Don't show the remove apps script.
- Don't show the telemetry/privacy things.

**Comment by Belim** [comment]
i like the idea 👍 but many pages could still be omitted. especially if you got to know the operating system, you don't want to go through it again and again.  we also don't know yet what new features microsoft will add or what existing ones will be removed . nothing is really official yet.

in the end only tweaking, scripting, packing functions might remain 😁
