### ISSUE TITLE
I can't get back to first state

### ISSUE THREAD

**Issue by CobKurtain** [builtbybel/ThisIsWin11#20]
Every settings were checked by the soft and when I try to get everything back as I wanted to be, it stays as the soft want

**Comment by Belim** [comment]
check this https://github.com/builtbybel/ThisIsWin11/issues/4

**Comment by Belim** [comment]
just select each option you want to restore to the default state and press "Restore...". (of course without pressing the <Check> button).

**Comment by Belim** [comment]
don't forget to restart
