### ISSUE TITLE
Restore Defaults

### ISSUE THREAD

**Issue by Mctooo** [builtbybel/ThisIsWin11#200]
Stops at 

![2023-01-01 17_27_25-Einstellungen](https://user-images.githubusercontent.com/76923377/210177950-d487beac-83b3-47d5-8390-2bdabd6aad45.png)

Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.IO.FileNotFoundException: Die Datei "C:\Users\fehre\Downloads\TIW11\TIW11\data\spy.txt" konnte nicht gefunden werden.
Dateiname: "C:\Users\fehre\Downloads\TIW11\TIW11\data\spy.txt"
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   bei System.IO.StreamReader..ctor(String path, Encoding encoding)
   bei System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   bei ThisIsWin11.OpenTweaks.Assessment.Paranoia.WindowsSpyBlocker.UndoAssessment()
   bei ThisIsWin11.CustomizeWindow.<>c__DisplayClass18_0.<UndoAssessments>b__0()
   bei System.Threading.Tasks.Task`1.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   bei ThisIsWin11.CustomizeWindow.<UndoAssessments>d__18.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.9105.0 built by: NET481REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
----------------------------------------
ThisIsWin11
    Assembly-Version: 1.4.0.0.
    Win32-Version: 1.4.0.
    CodeBase: file:///C:/Users/fehre/Downloads/TIW11/TIW11/ThisIsWin11.exe.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.9075.0 built by: NET481REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.9065.0 built by: NET481REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.9032.0 built by: NET481REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.9032.0 built by: NET481REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.9115.0 built by: NET481REL1LAST_B.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.9032.0 built by: NET481REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
System.Management.Automation
    Assembly-Version: 3.0.0.0.
    Win32-Version: 10.0.22621.963.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management.Automation/v4.0_3.0.0.0__31bf3856ad364e35/System.Management.Automation.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.9032.0 built by: NET481REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------
mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.9032.0 built by: NET481REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
----------------------------------------
Microsoft.PowerShell.Commands.Diagnostics
    Assembly-Version: 3.0.0.0.
    Win32-Version: 10.0.22621.1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Commands.Diagnostics/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Commands.Diagnostics.dll.
----------------------------------------
System.Management.Automation.resources
    Assembly-Version: 3.0.0.0.
    Win32-Version: 10.0.22621.608.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management.Automation.resources/v4.0_3.0.0.0_de_31bf3856ad364e35/System.Management.Automation.resources.dll.
----------------------------------------
System.Configuration.Install
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.9032.0 built by: NET481REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration.Install/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.Install.dll.
----------------------------------------
Microsoft.PowerShell.ConsoleHost
    Assembly-Version: 3.0.0.0.
    Win32-Version: 10.0.22621.1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.ConsoleHost/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.ConsoleHost.dll.
----------------------------------------
Microsoft.PowerShell.Commands.Utility
    Assembly-Version: 3.0.0.0.
    Win32-Version: 10.0.22621.1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Commands.Utility/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Commands.Utility.dll.
----------------------------------------
Microsoft.PowerShell.Commands.Management
    Assembly-Version: 3.0.0.0.
    Win32-Version: 10.0.22621.608.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Commands.Management/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Commands.Management.dll.
----------------------------------------
Microsoft.Management.Infrastructure
    Assembly-Version: 1.0.0.0.
    Win32-Version: 10.0.22621.1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Management.Infrastructure/v4.0_1.0.0.0__31bf3856ad364e35/Microsoft.Management.Infrastructure.dll.
----------------------------------------
Microsoft.PowerShell.Security
    Assembly-Version: 3.0.0.0.
    Win32-Version: 10.0.22621.1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Security/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Security.dll.
----------------------------------------
Microsoft.WSMan.Management
    Assembly-Version: 3.0.0.0.
    Win32-Version: 10.0.22621.1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.WSMan.Management/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.WSMan.Management.dll.
----------------------------------------
System.Data
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.9110.0 built by: NET481REL1LAST_B.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll.
----------------------------------------
System.Management
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.9032.0 built by: NET481REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll.
----------------------------------------
System.DirectoryServices
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.9032.0 built by: NET481REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.DirectoryServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.DirectoryServices.dll.
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly-Version: 0.0.0.0.
    Win32-Version: 4.8.9105.0 built by: NET481REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll.
----------------------------------------
System.Numerics
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.9032.0 built by: NET481REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll.
----------------------------------------
System.Transactions
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.9032.0 built by: NET481REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll.
----------------------------------------
Microsoft.PowerShell.Security.resources
    Assembly-Version: 3.0.0.0.
    Win32-Version: 10.0.22621.1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Security.resources/v4.0_3.0.0.0_de_31bf3856ad364e35/Microsoft.PowerShell.Security.resources.dll.
----------------------------------------
Microsoft.WSMan.Management.resources
    Assembly-Version: 3.0.0.0.
    Win32-Version: 10.0.22621.1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.WSMan.Management.resources/v4.0_3.0.0.0_de_31bf3856ad364e35/Microsoft.WSMan.Management.resources.dll.
----------------------------------------
Microsoft.Dism.PowerShell
    Assembly-Version: 10.0.0.0.
    Win32-Version: 10.0.22621.1.
    CodeBase: file:///C:/Windows/system32/WindowsPowerShell/v1.0/Modules/Dism/Microsoft.Dism.PowerShell.dll.
----------------------------------------
Microsoft.PowerShell.Commands.Utility.resources
    Assembly-Version: 3.0.0.0.
    Win32-Version: 10.0.22621.1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Commands.Utility.resources/v4.0_3.0.0.0_de_31bf3856ad364e35/Microsoft.PowerShell.Commands.Utility.resources.dll.
----------------------------------------
Microsoft.Dism.PowerShell.resources
    Assembly-Version: 10.0.0.0.
    Win32-Version: 10.0.22621.1.
    CodeBase: file:///C:/Windows/system32/WindowsPowerShell/v1.0/Modules/Dism/de/Microsoft.Dism.PowerShell.resources.DLL.
----------------------------------------

************** JIT-Debuggen **************
Um das JIT-Debuggen (Just-In-Time) zu aktivieren, muss in der
Konfigurationsdatei der Anwendung oder des Computers
(machine.config) der jitDebugging-Wert im Abschnitt system.windows.forms festgelegt werden.
Die Anwendung muss mit aktiviertem Debuggen kompiliert werden.

Zum Beispiel:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Wenn das JIT-Debuggen aktiviert ist, werden alle nicht behandelten
Ausnahmen an den JIT-Debugger gesendet, der auf dem
Computer registriert ist, und nicht in diesem Dialogfeld behandelt.

**Comment by Belim** [comment]
download this file https://github.com/crazy-max/WindowsSpyBlocker/blob/master/data/hosts/spy.txt
and copy it to Data directory of TIW11. this is the reference file for un-/blocking

**Comment by Mctooo** [comment]
works thx

**Comment by thanantonop** [comment]
Cannot restore the improve inking and typing on Diagnostics & feedback
