### ISSUE TITLE
Toolbar Bug 🐛 

### ISSUE THREAD

**Issue by EdgarGc026** [builtbybel/ThisIsWin11#204]
I execute ThisIsWin11.exe and the button "Fix issues", when it finish, the toolbar is bugged...  Any way to correct this "error"? 🐛
![image](https://user-images.githubusercontent.com/19244335/210277235-fafbdf0d-4373-4bad-aec4-62cbf17471f4.png)

Complete toolbar
![image](https://user-images.githubusercontent.com/19244335/210277384-92beb60a-015f-42fb-8c4f-ca3c2bf63fec.png)

**Comment by TheFrisianClause** [comment]
Yes there is a fix, as I have been running into this issue too, for the fix look at this url: 
https://pureinfotech.com/change-taskbar-size-windows-11/

**Comment by EdgarGc026** [comment]
> Yes there is a fix, as I have been running into this issue too, for the fix look at this url: https://pureinfotech.com/change-taskbar-size-windows-11/

Thanks for the reply. I fixed that 💪
