### ISSUE TITLE
Unrepairable Modifications, High Security Risk! 

### ISSUE THREAD

**Issue by ElessarElbenstein** [builtbybel/ThisIsWin11#221]
### Issue description

Gonna label the newest version as malmare, because it causes irreparable system changes that require a reinstall of windows.

Not working anymore:
Windows Store
Firewall
Security Center
Store Updates
Defender
Screenshot
Calculator

Anda whole bunch of other stuff.

Do not use this app or remove it. The amount of breakage the app now causes is irresponsible. Your better of turning stuff off by hand. 

### How to reproduce this issue?

Use any of the provided settings

### Details

Irrelevant it's not the system, it's the release Version of the app at current date

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/builtbybel/ThisIsWin11/issues' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not already fixed

**Comment by djinthegiant** [comment]
Works fine for me , nice spelling and grammar. That you Bill?

**Comment by Belim** [comment]
(ChatGPT)Bot
