### ISSUE TITLE
Context Menu Edition Support

### ISSUE THREAD

**Issue by CrypticCus** [builtbybel/ThisIsWin11#35]
Now 3rd party apps can deliver their own custom context menu like winrar. and there are apps to add custom context menu
https://github.com/ikas-mc/ContextMenuForWindows11

but no one added support for editing existing context menu items, also support for editing create>new context sub menu...
for exp .bmp and .txt cannot be removed. and also .ps1 cannot be added to windows 11's create>new menu.....

i expect this tool to handle this problem.

**Comment by Belim** [comment]
This is not planned to be introduced in TIW11

Such projects already exist, for instance. https://github.com/ikas-mc/ContextMenuForWindows11
