### ISSUE TITLE
deactivate/remove xbox gamebar 

### ISSUE THREAD

**Issue by DigitalNXZ** [builtbybel/ThisIsWin11#38]
It would be nice to get such a feature since I don't really like it and nvidia does the same tho
and if I would want to record or whatever I can use OBS for myself~ 

I deinstalled it myself but the problem there was games like Genshin asked for a ms-config overlay whatever.. reinstalled gamebar.. problem fixed ._. I would like to remove the gamebar without getting asked for missing apps "search in the store for recommended apps" it's somehow annoying :))

Would it be possible?

**Comment by andrewbaker-uk** [comment]
Just used the latest version of the app. Under one of the sections there is a tree view with gaming. Under gaming is a game bar option

**Comment by DigitalNXZ** [comment]
> Just used the latest version of the app. Under one of the sections there is a tree view with gaming. Under gaming is a game bar option

Oh I see, I think its the "Apps" one.. Ill try it, thanks for pointing it out!!
