### ISSUE TITLE
Guide how to restore a specific setting

### ISSUE THREAD

**Issue by ealap** [builtbybel/ThisIsWin11#4]
For some reason, restoring to Windows Default settings is not really doing it on my machine.

Now how do i restore each of them manually.

I specifically wanted to bring back Windows Hello Biometrics, but the steps I found on other sources are not working.

Using Windows 11 Home, build 22000.132

**Comment by tradaonline** [comment]
I need this feature too. Now my finger print not working anymore.

**Comment by abrondijk** [comment]
I want to revert back a setting to the default as well, but the option "Restore default Windows 11 settings" is not showing:
![image](https://user-images.githubusercontent.com/73667900/141174686-4b765747-afc4-4cc8-8b24-6e0f45b6fd98.png)

What am I doing wrong?

**Comment by Belim** [comment]
Here outlined in red

![140894581-4007a7a1-106c-4424-8e93-dba040bc43b9](https://user-images.githubusercontent.com/57478606/141180720-e17cb004-9233-49f5-b87e-ca969c54a911.png)

as of build 0.91 the button can be found here and it will remain there for the time being

![141170712-f0a3f356-aa3a-454d-8838-57e48f28cd11](https://user-images.githubusercontent.com/57478606/141180815-11ee8af4-c15e-47c4-9ce5-2eb1b8cf2fd7.png)

**Comment by xdagee** [comment]
Same here, I think you can't restore when you run the tweak

**Comment by Infinity-MC** [comment]
I disabled onedrive using the powershell script, how do I re-enable it?
