### ISSUE TITLE
Lost access to Calendar,Clock, and Volume.

### ISSUE THREAD

**Issue by Teck1015** [builtbybel/ThisIsWin11#41]
So...I'm probably just being stupid, but I did all the recommended checks in the "System" tab in ThisIsWin11, and now I've lost visibility of the Clock, Calendar and Volume icon in the lower right of the taskbar. What do I need to change to get them back? Thanks.

[Pic of My Taskbar](https://i.imgur.com/d9vmpNL.png)

**Comment by Belim** [comment]
just undo the `Third Party > Enable classic Taskbar with ExplorerPatcher` hack

Read here how to revert the changes
https://github.com/builtbybel/ThisIsWin11/issues/4
