### ISSUE TITLE
All messed up

### ISSUE THREAD

**Issue by xtasy-games** [builtbybel/ThisIsWin11#44]
After applying all recomended settings, it only worked fine until I rebooted. Now all is meesd up: usb keyboard keeps disconnecting, taskbar system icons are displaced, classic taskbar only worked once too, and later it didn't work again, and even cannot access its settings, I even lost start menu (start button is there but don't work), I had to install open shell to have a functional task bar. Volume keys don't work  (just up but no down) and don't show the classic selector, neither network. nor battery. All my system is a mess!! I will have to reinstall windows. Please review your code and try to add a "revert changes" button.

**Comment by Belim** [comment]
the code is fine 💯 
just undo your changes https://github.com/builtbybel/ThisIsWin11/issues/4
