### ISSUE TITLE
App broke my whole Windows 11

### ISSUE THREAD

**Issue by saschabrockel** [builtbybel/ThisIsWin11#45]
I'm not sure what this app does but I'm terrified to use it ever again. Since I've used this and just applied all settings I lost the new explorer bar (of course) but now it's flickering on every click I make in the explorer and I want to Windows 11 design back. There should be an option to revert everything.

**Comment by Belim** [comment]
this happend also here and it is not caused by TIW11 itself but rather by the ExplorerPatcher hack (`Option System > Third Party > Enable classic Taskbar...`)
Please undo your changes https://github.com/builtbybel/ThisIsWin11/issues/4

I think i will drop ExplorerPatcher support in TIW11

**Comment by saschabrockel** [comment]
Nope. Does not work. That is what I meant. This ExplorerPatcher completely broke my Windows Explorer. How can I undo this horrible nightmare? As it says because it is already deleted: `C:\WINDOWS\dxgi.dll` could not be found

**Comment by notbluu** [comment]
Try using System Restore on your PC & restore before you initially used the tool.

**Comment by saschabrockel** [comment]
Multiple restarts and maybe updates worked out. Thanks anyway. But really don't use this Explorer Patcher!
