### ISSUE TITLE
Hang on uninstalling widgets

### ISSUE THREAD

**Issue by death2all110** [builtbybel/ThisIsWin11#46]
It seems that if you have not used winget previously, windows will prompt you in powershell/command prompt to accept terms. However, since the app hides the powershell/command prompt window, the user does not get the option to accept or refuse the terms. I had to run winget in a separate powershell window and accept the terms before TIW11 would move past 'Uninstalling Widgets'. 

Other than that, great work!

**Comment by Belim** [comment]
Thanks, will be fixed in upcoming build

**Comment by Belim** [comment]
Think this should be fixed here https://github.com/builtbybel/ThisIsWin11/releases/tag/0.91.0
