### ISSUE TITLE
Additional Win11 bloat

### ISSUE THREAD

**Issue by TotallyMonica** [builtbybel/ThisIsWin11#47]
The following apps are included in some, maybe not all, installs of Win11:
LINE
Whatsapp
Lightroom
Messenger
Photo editor
Picsart
Clipchamp

I'd submit a pull request but I don't know offhand how to get the ID of those apps, maybe `winget` would have it? I'll follow up if I can get more info

**Comment by TotallyMonica** [comment]
Looks like clipchamp is Clipchamp.Clipchamp_yxz26nhyzhsrt
Picsart is 2FE3CB00.PICSART-PHOTOSTUDIO_crhqpqs3x1???
Lightroom is: AdobeSystemsIncorporated.AdobeLightroom_???
Messenger: FACEBOOK.317180B0BB486_8xx8rvfyw5nnt
WhatsApp: 5319275A.WhatsAppDesktop_cv1g1gvanyjgm
LINE: NAVER.LINEwin8_8ptj331gd3tyt
PaintShop (What was photo editor in my initial comment): CorelCorporation.PaintShopPro_wbjqpk9xt5???

**Comment by Belim** [comment]
Thanks, your pull request have been merged 👍
