### ISSUE TITLE
.exe crashing after fixing 

### ISSUE THREAD

**Issue by Mattman875** [builtbybel/ThisIsWin11#50]
after running the system fix the app runs and then closes, and the .exe file in the TIW11 folder disappears

**Comment by Belim** [comment]
the .exe file disappears 🤔 What tweak did you apply to force this behaviour?
Maybe your AV guard has struck after enabling certain tweaks.

**Comment by Mattman875** [comment]
I just ran the system tab, with all boxes checked, ran for a couple seconds and then quit. I ran through the other tabs and everything works and am satisfied, only problem is my taskbar is a bit jiggered. the date portion is cut off and my icons have shrunk.

**Comment by Belim** [comment]
>  I just ran the system tab, with all boxes checked, ran for a couple seconds and then quit. 

does this continues to happen? we would have to narrow it down to (the) one tweak. I have never been able to observe this kind of crash

`  the date portion is cut off and my icons have shrunk.`
Yeah, a W11 and NOT TIW11 issue  😢

**Comment by Mattman875** [comment]
Yeah, I am thinking it's a firewall exception w/ the crashing, I added
TIW11 to the list and no more crashing. Sad about the taskbar issue, i've
since moved back to windows 10 😕. Appreciate what you've done to try to
make 11 palatable.

Cheers
