### ISSUE TITLE
Missing check and fix issues buttons.

### ISSUE THREAD

**Issue by lazygator2020** [builtbybel/ThisIsWin11#52]
Missing the check and fix issues buttons in control Settings.
Also missing buttons under Packages?
Latest build of ThisIsWin11
WIn11 Home build 22000.318
Tried different windows sizes, different resolutions ect.

**Comment by lazygator2020** [comment]
Fixed it. Scaling problem

**Comment by Belim** [comment]
Damn, I'm not able to reproduce this. 
It has already been reported here https://github.com/builtbybel/ThisIsWin11/issues/26

 What resolution and scaling is it?

**Comment by Belim** [comment]
can you please check this testing build
[TIW11_dev.zip](https://github.com/builtbybel/ThisIsWin11/files/7532629/TIW11_dev.zip)

**Comment by Belim** [comment]
https://github.com/builtbybel/ThisIsWin11/releases/tag/0.91.21
