### ISSUE TITLE
Game Pass Sign-in

### ISSUE THREAD

**Issue by GrizzyKreme** [builtbybel/ThisIsWin11#53]
After running the program I have not been able to use xbox game pass on PC. I didnt remove any of the xbox related apps but when attempting to sign in, the window closes instantly. I can sign into my microsoft account in windows but now into anything related to xbox. Is there a way to fix this?

**Comment by Belim** [comment]
Infortunately, I can't give you any tips here, as I don't use the Xbox app. I don't know what other dependencies the Xbox app might have. Try updating or resetting it.

**Comment by gohv** [comment]
Fairly certain the OP removed some of the Windows Gaming Services. 

Verify if they are running in Task Manager.

If not verify if they are present here:
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\GamingServices]
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\GamingServicesNet]

If not try to install:
get-appxpackage Microsoft.GamingServices | remove-AppxPackage –allusers

**Comment by andrewbaker-uk** [comment]
Just tried this on a clean install. During the uninstall apps section I selected all the apps bar the ones I needed (including the Xbox apps). I also had to set the Xbox services back to manual.

Was able to sign in fine.

**Comment by GrizzyKreme** [comment]
Thanks for the help. It was a problem with the services. I was able to get the xbox auth manager service working again and got the sign in prompt.
