### ISSUE TITLE
Scaling issues 

### ISSUE THREAD

**Issue by Guardian-AI-Dusty** [builtbybel/ThisIsWin11#54]
Hi there . I used the small icon option and it works however it seems like the icons on the top right corner have issues with it 
I know the changelog said it fixed it but somehow it isn't working out for me

![45cNJsR6Re](https://user-images.githubusercontent.com/79192743/141739781-32458519-e040-44e4-a323-74f3ec5228c9.png)

**Comment by Belim** [comment]
Hi,
no, the latest fixes are related to UI scaling issues within the app. I can't fix the issue you mentioned because it's a Win11 bug.

**Comment by hemmigumm** [comment]
I understand that this is a Win11 bug, but are there any plans/ideas for a workaround?

**Comment by Belim** [comment]
At present, that is Un-fixable as its a MS thing

**Comment by gohv** [comment]
I can confirm its a MS issue, but can be undone. They screwed up the scaling if the value is 0.

If you use the small icons feature you can just edit the registry here:
**Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced**
Key:  **TaskbarSi**
Value: 1 or 2 or 3 or 4 or you get my meaning, should be > 0

**Comment by TermNCR** [comment]
@gohv Thanks so much man! I set a value of 1 and back to normal. 
![image](https://user-images.githubusercontent.com/35748951/142228996-10d1a8eb-bc54-48eb-a18f-73c83700dccd.png)

**Comment by hemmigumm** [comment]
This fix only returns the taskbar to the default height, still no way to scale it correctly with the small taskbar.

**Comment by Belim** [comment]
just undo your changes in TIW11
https://github.com/builtbybel/ThisIsWin11/issues/62
