### ISSUE TITLE
Taskbar slipping date and time

### ISSUE THREAD

**Issue by racskobalazs** [builtbybel/ThisIsWin11#62]
Hi, I have a weird issue. 

I don't exactly know which function does this, but when I run the "script", my date and time section of my taskbar slips downwards.

![image](https://user-images.githubusercontent.com/20138809/143091917-1d156112-a3d0-4145-a6c1-2eaa7d1c3c57.png)

Does this have a fix? 

Thanks in advance.

**Comment by Belim** [comment]
https://github.com/builtbybel/ThisIsWin11/issues/54

or just undo this tweak
![Image 2](https://user-images.githubusercontent.com/57478606/143194921-4bdd9c08-2f34-4a59-8494-150c05e8f0b0.png)
