### ISSUE TITLE
Missing taskbar items

### ISSUE THREAD

**Issue by Energyblast** [builtbybel/ThisIsWin11#63]
I used this and my volume, network, and clock disappeared from my task bar. I cannot find them in my taskbar settings. Can someone help me please

**Comment by ryanmusante** [comment]
What was the fix for this??

**Comment by Energyblast** [comment]
> What was the fix for this??

Sorry I should've included what I did. I just downloaded the latest ExplorerPatcher https://github.com/valinet/ExplorerPatcher/releases/tag/22000.348.39.1_493cf27
it set my things back to normal

**Comment by ryanmusante** [comment]
Perfect. This is workaround for win11 bug.
