### ISSUE TITLE
Undo: Hide taskbar on multiple monitors

### ISSUE THREAD

**Issue by ux4real** [builtbybel/ThisIsWin11#64]
I have a problem with "Restore default Windows 11 settings". When I start it, the process freezes at the stage of "Undo: Hide taskbar on multiple monitors".

![2021-11-26_143743](https://user-images.githubusercontent.com/68108545/143589768-2d5acf7b-7789-473f-80b9-c55017fd98fa.jpg)

**Comment by Belim** [comment]
After the explorer.exe process is terminated, it is immediately restarted. Apparently the explorer.exe cannot be started on your system.

Does applying the tweak works for you?
