### ISSUE TITLE
Running Update Apps in Windows store fails

### ISSUE THREAD

**Issue by rokeno** [builtbybel/ThisIsWin11#66]
I have tried running the script standalone and in a Admin as Terminal window i get:

```
InvalidOperation: TIW11\data\scripts\(Apps) Update Store apps.ps1:6
Line |
   6 |  $result = $wmiObj.UpdateScanMethod()
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Method invocation failed because
     | [Deserialized.System.Management.ManagementObject#root\cimv2\mdm\dmmap\MDM_EnterpriseModernAppManagement_AppManagement01] does not contain a method named 'UpdateScanMethod'.
```

**Comment by Belim** [comment]
🤔 no probs. here... anyone else?

**Comment by wise-io** [comment]
> 🤔 no probs. here... anyone else?

This error appears to occur when using PowerShell 7, but not when using PowerShell 5.1 (built-in).

**Comment by shanewalsheire** [comment]
Get-WmiObject is not supported on PowerShell 7. Use Get-CimInstance instead.

Get-CimInstance -Namespace "Root\cimv2\mdm\dmmap" -ClassName "MDM_EnterpriseModernAppManagement_AppManagement01" | Invoke-CimMethod -MethodName UpdateScanMethod
