### ISSUE TITLE
Rolled back Apps Permissions and WindowsSpyBlocker but still cannot access microsoft store

### ISSUE THREAD

**Issue by brimwats1** [builtbybel/ThisIsWin11#71]
Am I missing a checkbox to reenable microsoft store? I want(ed) to use Nebo, but it looks like it needs to access the internet for account features. I'm not sure which feature I'd rollback for that, or if there is one

**Comment by brimwats** [comment]
if anyone runs into this issue in the furture, what I did was to revert to the restore point pre ThisIsWin11. This hasn't fixed the issue with Nebo, however (it still thinks I'm not connected to the internet), and I need to investigate further :(

**Comment by brimwats** [comment]
I am still locked out of Microsoft Store, even after following steps to restore it. Waiting to see if there's anything else I've missed in ThisIsWin11 to reenable microsoft store

**Comment by brimwats** [comment]
alright, I don't know what to do with this—you can feel free to close it if you want, but microsoft store is irretrievably fucked on my account now, I spent about 18 hours trying different things

**Comment by Belim** [comment]
You can enable all the settings in TIW11 and you won't be able to break the store. This is also not possible with the WindowsSpyBlocker rules available in TIW11. Something else must be the trigger..

**Comment by brimwats** [comment]
I feel like it must be, right? But I ran TIW11 on both my desktop and laptop at the same time. It worked fine on my desktop, but on my laptop it immediately broke. I endlessly get error code `0x80131500`.

> Did you maybe uninstall the Store app? Try re-instslling it..

I've done the following so far: 

1. `wsreset.exe` to reset the store
2. Followed everything microsoft suggested [here](https://support.microsoft.com/en-us/account-billing/fix-problems-with-apps-from-microsoft-store-93ed0bcf-9c12-3df6-6dda-92ec5d0415ac#WindowsVersion=Windows_11) (ran windows update, repaired the store, rest the store)
3. Re-registered all store apps via `Get-AppXPackage -AllUsers | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}`
4. Deleted and reinstalled the store `Get-AppxPackage -allusers *WindowsStore* | Remove-AppxPackage` and `Get-AppxPackage -allusers *WindowsStore* | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register “$($_.InstallLocation)\AppXManifest.xml”}`
5. Disabled antivirus
6. Changed region settings in my online profile. 
7. Tried to switch to a different user by signing out and then back in. For that I run into error `0x80190001`.
8. Created a new user on my computer using the old administrator options, which worked. The new user is able to access the store fine. I would guess if I wan TIW11 it would break for that user as well, but I haven't tried it yet.
9. Rolling back everything in TIW11. multiple times. 
10. A few different forum pages suggest checking/unchecking variations on SSL/TLS settings. Some suggest to unselect SSL 3.0 and TLS 1.0 and 1.1 and select TLS 1.2 and (If Available) TLS 1.3. Others suggest to keep TLS 1.0 and 1.1. None have worked so far. 

I've repeated all of these steps multiple times and in several different orders. Sometimes the "homepage" of the Microsoft Store loads, but nothing more than that. Clicking on "library" or anywhere else triggers 0x80131500 again.

**Comment by shink3n1** [comment]
Yeah, Windows Spy Blocker rules blocked whatever IP address is used to connect to the Microsoft Store for me too. I'm getting 0x80131500. There needs to be a way to roll this back.

**Comment by Belim** [comment]
Just use the restore function of the app
https://github.com/builtbybel/ThisIsWin11/issues/4

**Comment by shink3n1** [comment]
I did. It removed the firewall rules, but the Store is still offline. Tried repair and reset for Microsoft Store app to no avail.

**Comment by shink3n1** [comment]
Apologies, it turns out the issue has nothing to do with ThisisWin11 or WindowsSpyBlocker. It has to do with my VPN. Likely PIA or Microsoft recently blacklisted the other’s DNS or vice versa, because they MS Store had been working fine that way until very recently. Sorry about that.

**Comment by brimwats1** [comment]
Just noting here: the only way to dix this is to make a new microsoft account and start over. The issue can be closed otherwise
