### ISSUE TITLE
Small taskbar icons cut off date

### ISSUE THREAD

**Issue by BenChoat** [builtbybel/ThisIsWin11#74]
After using the app (version 0.94.0) on a fresh install of Windows 11 on a Surface Pro 7+, the date in the taskbar is cutoff, presumably from selecting small taskbar icons. After following instructions here (https://www.tomshardware.com/how-to/change-taskbar-icon-size-windows-11) and changing icon size back to medium, the time and date appear as expected.

**Comment by Belim** [comment]
https://github.com/builtbybel/ThisIsWin11/issues/54

**Comment by sakkiepretoria** [comment]
Is there a way to keep a smaller (Lower hight) Taskbar and then realign the time and date to maybe be next to each other instead of above and below?
