### ISSUE TITLE
Windows Defender detects Trojan:Script/Wacatac.B!ml in WIT11.zip

### ISSUE THREAD

**Issue by BLT2GoBus** [builtbybel/ThisIsWin11#76]
Windows Defender detects Trojan:Script/Wacatac.B!ml in WIT11.zip.  Should this be ignored?

**Comment by Belim** [comment]
Yeah, this can be ignored as the Powershell scripts are flagged as meeting heuristic patterns.
The .EXE is clean https://www.virustotal.com/gui/file/dbef240917215ec6c0aa7f9a6d0982814b8c73867db98185c5ddba51f74d64b0?nocache=1
