### ISSUE TITLE
Complete rollback mechanism missing

### ISSUE THREAD

**Issue by rarnold99** [builtbybel/ThisIsWin11#78]
Dear colleagues, thanks for the phantastic work and system! Very handy and useful tool. As a final touch I miss a robust and reliable rollback mechanism and a log file with a list of changes in the Windows registry. Would be great to this in the near future.

**Comment by Belim** [comment]
What exactly are you talking about? 

The **System/OpenTweaks** module includes a restore and log function. See here https://github.com/builtbybel/ThisIsWin11/issues/4 Any changes in the regisitry are documented and can be rolled back.

The same applies to the **Automate/PowerUI** module where each script can be viewed and also applied scripts can be displayed _(Just click on three dots/More Options menu > Show applied)_
