### ISSUE TITLE
[Extensions module] Run as administrator

### ISSUE THREAD

**Issue by oleksis** [builtbybel/ThisIsWin11#79]
Run as administrator the path to the **plugins** folder is `C:\WINDOWS\system32\`

![image](https://user-images.githubusercontent.com/44526468/145961513-e7211e6c-0de2-4a80-bc5f-fd504d317189.png)

**Comment by Belim** [comment]
Damn, what is that 😕 
Im administrator here and am redirected to the plugins data directory and am aware of no such thing.  The app is running with `highestAvailable` ExecutionLevel .

thats the call
`=> Process.Start("explorer.exe", @"data\plugins");`

Maybe switching to [ShellExecuteExW](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellexecuteexw) function ..

**Comment by oleksis** [comment]
I think the best way is concatenation with the absolute path from the executable.

**Comment by Vichingo455** [comment]
Just copy data folder in C:\Windows\System32

**Comment by Belim** [comment]
does it work in latest builds

**Comment by oleksis** [comment]
Yes the version 1.0.70 fix the issue.
