### ISSUE TITLE
Feature request: Add extension AutoAdminLogon

### ISSUE THREAD

**Issue by oleksis** [builtbybel/ThisIsWin11#80]
Enable automatic logging in **Windows 11** with one default user.

Work with the reg keys:

```.reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon]
"AutoAdminLogon"="1"
"DefaultUserName"="__USERNAME__"
"DefaultPassword"="__PASSWORD__"


```

In this branch ([AutoAdminLogon](https://github.com/oleksis/ThisIsWin11/commit/aa15aa642bdc33658648fba6edea8e50294b1738)) have the plugin file and the scripts. This case we need add middle step for ask for the default **UserName** and **Password** and update the scripts; replace `__USERNAME__` and `__PASSWORD__`  and then run the .bat

If sound good i send the PR

**Comment by Belim** [comment]
Yes, please keep 'em coming

**Comment by Vichingo455** [comment]
> Enable automatic logging in **Windows 11** with one default user.
> 
> Work with the reg keys:
> 
> ```reg
> Windows Registry Editor Version 5.00
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon]
> "AutoAdminLogon"="1"
> "DefaultUserName"="__USERNAME__"
> "DefaultPassword"="__PASSWORD__"
> ```
> 
> In this branch ([AutoAdminLogon](https://github.com/oleksis/ThisIsWin11/commit/aa15aa642bdc33658648fba6edea8e50294b1738)) have the plugin file and the scripts. This case we need add middle step for ask for the default **UserName** and **Password** and update the scripts; replace `__USERNAME__` and `__PASSWORD__` and then run the .bat
> 
> If sound good i send the PR

For username, in batch we have the variable `%username%` that equals to the logged user's username

**Comment by Belim** [comment]
> For username, in batch we have the variable `%username%` that equals to the logged user's username

yeah 😃 
`REG ADD "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" /V DefaultUserName /T REG_SZ /D %Username% /F`

But how to handle the Password field 🤔 Maybe just adding a messagebox
`msg "%username%" "Please add a Password for the currently logged user here: HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon |DefaultPassword:"`

**Comment by Vichingo455** [comment]
> > For username, in batch we have the variable `%username%` that equals to the logged user's username
> 
> yeah 😃 `REG ADD "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" /V DefaultUserName /T REG_SZ /D %Username% /F`
> 
> But how to handle the Password field 🤔 Maybe just adding a messagebox `msg "%username%" "Please add a Password for the currently logged user here: HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon |DefaultPassword:"`

Issue: Microsoft Accounts have been started to have no password
