### ISSUE TITLE
Bypass edge as default handler for web searches (Automated tasks). Doesnt work for me

### ISSUE THREAD

**Issue by lenti21** [builtbybel/ThisIsWin11#83]
When trying to apply this tweak it doesnt work. It gets stuck in powershell.

**Comment by Belim** [comment]
today PR https://github.com/builtbybel/ThisIsWin11/pull/86 has been submitted.
Can you check latest version 2.0 of this script ?https://github.com/AveYo/fox/commit/19914c3d1f0d085836fd52efeee8ec266e836663

Its not yet added to TIW11

**Comment by lenti21** [comment]
It still gets stucked when in command prompt. But is it supposed to get stuck there?

**Comment by Belim** [comment]
@rcmaehl any ideas?

**Comment by rcmaehl** [comment]
> @rcmaehl any ideas?

As long as it's running as an admin powershell it should be fine. @aveyo is usually active and may have a better idea as it's his script. @lenti21 If you has any error messages or anything please provide them.

**Comment by AveYo** [comment]
Description is severely lacking, I suppose the script halts even before doing any work?
If you enter this in a standard powershell window (non-admin):
``` ps1
start -verb runas powershell -args "-nop -noe -c & {`n`n new-item 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\msedge.exe\1' -force -ea 0 `n`n}"
```
does it prompt for elevation and opens a new window with
*Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\msedge.exe*
*Name                           Property*
*----                           --------*
*1*
It should, else UAC is misconfigured and/or powershell is broken or hindered

An antivirus with lame heuristics might block the script or hinder powershell, 
so @lenti21 check your av notifications / exclude the script manually / temporarily disable the av

**Comment by lenti21** [comment]
I think it applied now. Can i see it in services.msc?

**Comment by rcmaehl** [comment]
> I think it applied now. Can i see it in services.msc?

You can check using 
`reg query "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\msedge.exe" /s` in command prompt or powershell

**Comment by lenti21** [comment]
It says: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\msedge.exe
    Debugger    REG_SZ    wscript C:\ProgramData\ChrEdgeFkOff.vbs //B //T:5 

Does it mean that it is applied?

**Comment by rcmaehl** [comment]
> It says: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\msedge.exe Debugger REG_SZ wscript C:\ProgramData\ChrEdgeFkOff.vbs //B //T:5
> 
> Does it mean that it is applied?

Should be good
