### ISSUE TITLE
Minecraft for windows cannot be installed

### ISSUE THREAD

**Issue by VilotStar** [builtbybel/ThisIsWin11#84]
After running this program and carefully selecting features, I tried to install Minecraft but I am now getting errors, the one error (this is all the info I can get) I get from Microsoft Store is, "something happened on our end".
I have been debugging this issue for 2 days now and reinstalled Windows 10 and 11, Although I do have another computer running a older version of Windows 10, with the non-updated store like newer 10s and 11s, and for whatever reason that computer can run Minecraft, (When I say Windows 10 I'm using the tool privatezilla not this tool, I'm only placing this issue here as I'm hoping people will be able to help)

**Comment by Belim** [comment]
Why must the problem have been caused by Privatezilla ?(even this is the wrong repository)

**Comment by Belim** [comment]
Why must the problem have been caused by Privatezilla ?(even this is the wrong repository) millions of other problems could be the cause. you won't find the solution here

**Comment by squaredindex** [comment]
I also have this issue. Only after using this tool. Minecraft now requires a Microsoft account, I would just get one for this but it seems as though the connection is being blocked, but I'm not sure exactly which setting I need to undo to resolve this.
