### ISSUE TITLE
Navigation buttons at bottom aren't visible

### ISSUE THREAD

**Issue by halfninja** [builtbybel/ThisIsWin11#85]
1920x1080 13" laptop display at recommended 150% scale - the bottom of the UI is cut off. If I switch to 100% scale and restart the app the buttons are there, so there are some incorrect layout calculations going on somewhere.

![image](https://user-images.githubusercontent.com/72052/147109101-3bdd5dff-b71e-49d1-a715-a5d4962be4bf.png)

**Comment by Belim** [comment]
I don't have a <15" Laptop to hand but can you test this build? 
[TIW11_dev.zip](https://github.com/builtbybel/ThisIsWin11/files/7763731/TIW11_dev.zip)

Maybe i guessed right 😸

**Comment by halfninja** [comment]
Thanks for the fast response! Sadly this build looks the same.

**Comment by Belim** [comment]
I have a W11 laptop in hand again soon (maybe today) then it will be fixed 🥷  Please be patient

**Comment by halfninja** [comment]
Of course, no rush! I've got a workaround for now which is to set the compatibility setting for scaling to System, which makes the app think it's at 100% scale, at the cost of making text blurry.

**Comment by Belim** [comment]
😃you could try this version in the meantime 
https://github.com/builtbybel/ThisIsWin11/releases/tag/1.0.20

**Comment by Belim** [comment]
fixed here fixed https://github.com/builtbybel/ThisIsWin11/releases/tag/1.0.40

**Comment by Belim** [comment]
fixed https://github.com/builtbybel/ThisIsWin11/releases/tag/1.0.40

**Comment by halfninja** [comment]
Can confirm it's now looking great on my machine. Thanks and merry christmas! 🎄
