### ISSUE TITLE
Package installer is not installing anything

### ISSUE THREAD

**Issue by CathalPh** [builtbybel/ThisIsWin11#87]
Just used the ThisIsWin11 for the first time. Great loved it but the Package Installer doesn't do anything. I selected the packages, created the package, ran the installer. Continued with the rest of the set up. Restarted and theres nothing there. Tried it again no software is installed even though the window on the left says they are installed and finished.

**Comment by Belim** [comment]
Can you check latest release?
https://github.com/builtbybel/ThisIsWin11/releases/tag/1.0.40
and give me the exception output
