### ISSUE TITLE
[ENHANCEMENT] Window much big

### ISSUE THREAD

**Issue by Vichingo455** [builtbybel/ThisIsWin11#89]
Please fix the much big Window, starting the program as maximized
![image](https://user-images.githubusercontent.com/59311016/147414365-e983a710-ff23-48cc-8be6-1a7ab2fedd3a.png)

**Comment by Vichingo455** [comment]
![image](https://user-images.githubusercontent.com/59311016/148097593-76bf20f5-174b-4185-b91c-5317eab46348.png)

**Comment by Belim** [comment]
I see. Can you please check this
[TIW11_dev.zip](https://github.com/builtbybel/ThisIsWin11/files/7814291/TIW11_dev.zip) ?

**Comment by Vichingo455** [comment]
Change windowstate to maximized on MainWindow.cs:
![image](https://user-images.githubusercontent.com/59311016/148239435-820bf24e-8d79-4e95-8856-044f09f9bfe5.png)

**Comment by Belim** [comment]
Can you check this [TIW11_dev.zip](https://github.com/builtbybel/ThisIsWin11/files/7821410/TIW11_dev.zip)?

**Comment by Vichingo455** [comment]
> Can you check this [TIW11_dev.zip](https://github.com/builtbybel/ThisIsWin11/files/7821410/TIW11_dev.zip)?

This afternoon I will check it

**Comment by Vichingo455** [comment]
Nothing :(
![image](https://user-images.githubusercontent.com/59311016/148398252-4a8dd480-4f8a-4949-87c7-818371e56abf.png)

**Comment by Belim** [comment]
What is the size and resolution of your laptop?
Is a bit tricky since i would have to exclude taskbars and docked windows or reduce the UI size for a small screens. I find it easier to maximize the application right away. If you then put in a scaling you have to maximize either way

**Comment by Vichingo455** [comment]
> What is the size and resolution of your laptop? Is a bit tricky since i would have to exclude taskbars and docked windows or reduce the UI size for a small screens. I find it easier to maximize the application right away. If you then put in a scaling you have to maximize either way
> 
> I will probably leave it like this for now

1920x1080

**Comment by Belim** [comment]
more precise description here https://github.com/builtbybel/ThisIsWin11/issues/110

**Comment by rcmaehl** [comment]
Windows recommends a minimum screen resolution of 720p. Accounting for a task bar (but NOT scaling), the max a window should start out at is ~1200x675
