### ISSUE TITLE
Settings managed by organization

### ISSUE THREAD

**Issue by MarvelDc97** [builtbybel/ThisIsWin11#94]
After using ThisIsWin11, my settings now say “some settings are managed by your organization” and are greyed out. Can this be fixed so I have control over my settings again?

**Comment by Belim** [comment]
Simply select all the options you have enabled in **Customization/OpenTweaks**  module and reset them to the default value by using the restore function

![Bild 3](https://user-images.githubusercontent.com/57478606/148173194-16baf7b3-736e-4f75-a6a7-256095a193dc.png)

**Comment by 2sk00pz** [comment]
Can the MS Store app be restored from OpenTweaks?
